name: Build

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches: [master]
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [no-intro, redump]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # https://github.com/actions/checkout

    - name: Setup Python
      uses: actions/setup-python@v3  # https://github.com/actions/setup-python
      with:
        python-version: 3.9.6

    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-${{ matrix.script }}.txt

    - name: Generate
      run: python ${{ matrix.script }}.py

    - name: Create release
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
      uses: ncipollo/release-action@v1  # https://github.com/ncipollo/release-action
      with:
        name: Nightly
        tag: Nightly
        artifacts: "*.xml,*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        body: Released by github actions
        commit: master

    - name: Upload Artifacts
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v3  # https://github.com/actions/upload-artifact
      with:
        name: ${{ matrix.script }}
        path: |
          *.xml
          *.zip
