name: Daily build

on:
    push:
      branches:
        - master
    schedule:
        - cron:  '0 5 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9.6

        - name: Install python requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Get No-intro
          id: generator_no_intro
          run: python no-intro.py

        - name: Get Redump
          id: generator_redump
          run: python redump.py

        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            name: Nightly
            tag_name: Nightly
            files: |
              *.xml
              *.zip
            fail_on_unmatched_files: true
            body: Released by github actions
