name: Daily build

on:
    push:
      branches:
        - master
    schedule:
        - cron:  '0 5 * * *'
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9.6

        - name: Install python requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

    no_intro:
        runs-on: ubuntu-latest
        needs: setup
        steps:
        - name: Get No-intro
          id: generator_no_intro
          run: python no-intro.py

    redump:
        runs-on: ubuntu-latest
        needs: setup
        steps:
        - name: Get Redump
          id: generator_redump
          run: python redump.py

    release:
        runs-on: ubuntu-latest
        needs: [no_intro, redump]
        steps:
        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            name: Nightly
            tag: Nightly
            artifacts: "*.xml,*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            body: Released by github actions
            commit: master
