name: Daily dat files

on:
    push:
    schedule:
        - cron:  '0 4 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9.6

        - name: Install python requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Download dats and generate profile.xml
          id: generator_redump
          run: python redump.py

        - name: Download dats and generate profile.xml
          id: generator_no_intro
          run: python no-intro.py

        - name: Upload assets to release
          uses: meeDamian/github-release@2.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: latest
            name: latest
            allow_override: true
            gzip: false
            files: >
                redump.xml
                redump.zip
                no-intro.xml
                no-intro.zip
