name: Nightly

on:
    push:
      branches:
        - master
    schedule:
        - cron:  '0 0 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            script: [no-intro, redump]

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9.6

        - name: Install python requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-${{ matrix.script }}.txt

        - name: Generate
          run: python ${{ matrix.script }}.py

        - name: Create release
          uses: ncipollo/release-action@v1
          with:
            name: Nightly
            tag: Nightly
            artifacts: "*.xml,*.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
            allowUpdates: true
            body: Released by github actions
            commit: master
