name: Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]

jobs:
  check-branch:
    name: Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Comment on Pull Request
        uses: mshick/add-pr-comment@v1
        if: github.base_ref != 'nightly'
        with:
          message: Pull requests must be made to the `nightly` branch. Thanks.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'

      - name: Fail Workflow
        if: github.base_ref != 'nightly' || ( github.base_ref != 'master' && github.head_ref != 'nightly' )
        run: |
          echo base: "$github_base_ref"
          echo head: "$github_head_ref"
          echo event base: "$github_event_pull_request_base_ref"
          echo event head: "$github_event_pull_request_head_ref"
          echo Base: "$GITHUB_BASE_REF"
          echo Head: "$GITHUB_HEAD_REF"
          exit 1
