name: Pull request test

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  build:
    name: Build dat archives
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Branch check
        if: ( github.head_ref == 'repo-sync/common-repo-files/default' && github.base_ref == 'master' ) || ( github.head_ref == 'nightly' && github.base_ref == 'master' )
        run: |
          echo Base: "$GITHUB_BASE_REF"
          echo Head: "$GITHUB_HEAD_REF"
          echo "branch=True" >> $GITHUB_ENV

      - name: Fail Workflow
        if: github.base_ref != 'nightly' && env.branch != 'True'
        run: |
          echo Base: "$GITHUB_BASE_REF"
          echo Head: "$GITHUB_HEAD_REF"
          exit 1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build No-intro
        id: generator_no_intro
        run: python no-intro.py

      - name: Build Redump
        id: generator_redump
        run: python redump.py
